### PR TITLE
[WIP] Add Forums

### PR DESCRIPTION
**Pull request by king601**
Adding forums to the Site. Still a bunch of work to do.

### CODE REVIEW

**Comment by king601** [comment]
DO NOT MERGE this PR until we get some more work implemented.

**Comment by king601** [comment]
Made good progress on it tonight. Base level features are in. 

Still need: 

- Trix Editor 
- Image Uploading with Trix Editor?
- Editing own posts
- Admin tools to rename posts/delete posts etc.
- Admin tool to reslug a post?
- Notifications

**Comment by king601** [comment]
Almost to the point where I'm satisfied with the initial implementation, considering pushing what I have live, but not switching the main links and letting some users in to test. 

Obviously I don't have any kind of user-to-user messaging in yet, that's on the agenda still

**Comment by shakycode** [comment]
@king601 if you want some help with the rest of your features and stories let me know.  I can assist with feature parity between branches.

**Pull request merged**
